language: c
sudo: required

install:
  - sudo apt-get install gfortran libnetcdf-dev libnetcdff-dev

script:
  - gfortran --version
  - nf-config --all
  - git clone https://github.com/geoschem/geos-chem.git Code_Dir
  - cd Code_Dir
  - make MET=geosfp GRID=4x5
