language: c
sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install gfortran libnetcdf-dev netcdf-bin

env:
  - CC=gcc CXX=g++ FC=gfortran NETCDF_HOME=/usr GC_BIN=/usr/bin GC_INCLUDE=/usr/include /usr/lib

script:
  - gfortran --version
  - nc-config --all
  - git clone https://github.com/geoschem/geos-chem.git Code_Dir
  - cd Code_Dir
  - make MET=geosfp GRID=4x5